name: Android build collections
description:

inputs:
  abi:
    description: target ABI
    required: false
    default: arm64-v8a

runs:
  using: composite
  steps:
    - name: Prepare NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        link-to-sdk: true
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Get gstreamer-android
      run: |
        mkdir -p ~/android/gst_root_android/
        pushd ~/android/gst_root_android/
        wget https://gstreamer.freedesktop.org/data/pkg/android/1.24.0/gstreamer-1.0-android-universal-1.24.0.tar.xz
        tar -xf gstreamer-1.0-android-universal-1.24.0.tar.xz
        popd
      shell: bash
    - name: Get nnstreamer
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer
        path: nnstreamer
    - name: Get nnstreamer-edge
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer-edge
        path: nnstreamer-edge
    - name: Get nnstreamer-android-resource
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer-android-resource
        path: nnstreamer-android-resource
    - name: NDK build
      run: |
        echo "NDK build, ${{ github.workspace }}"
        export GSTREAMER_ROOT_ANDROID=~/android/gst_root_android/
        export NNSTREAMER_ROOT=${{ github.workspace }}/nnstreamer
        export NNSTREAMER_EDGE_ROOT=${{ github.workspace }}/nnstreamer-edge
        export NNSTREAMER_ANDROID_RESOURCE=${{ github.workspace }}/nnstreamer-android-resource
        export ML_API_ROOT=${{ github.workspace }}
        if [ $TARGET_ABI == 'arm64-v8a' ]; then
          bash ${{ github.workspace }}/java/build-nnstreamer-android.sh --target_abi=$TARGET_ABI
        elif [ $TARGET_ABI == 'x86_64' ]; then
          bash ${{ github.workspace }}/java/build-nnstreamer-android.sh --target_abi=$TARGET_ABI --enable_nnfw=no
        else
          bash ${{ github.workspace }}/java/build-nnstreamer-android.sh --target_abi=$TARGET_ABI --enable_nnfw=no --enable_tflite=no
        fi

        result=$?
        if [[ ${result} -ne 0 ]]; then
          echo "NDK build failed"
          exit 1
        fi
      shell: bash
      env:
        TARGET_ABI: ${{ inputs.abi }}
