name: Android Build Test

on:
  pull_request:
    branches: [ main ]

  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64']
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
    - name: Prepare Android build
      uses: ./.github/actions/android-build
      with:
        abi: ${{ matrix.abi }}
    - name: Upload android library
      uses: actions/upload-artifact@v4
      with:
        name: android_lib_${{ matrix.abi }}
        path: ${{ github.workspace }}/android_lib
