name: Android Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64']
    steps:
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        link-to-sdk: true
    - name: Get gstreamer-android
      run: |
        mkdir -p ~/android/gst_root_android/
        pushd ~/android/gst_root_android/
        wget https://gstreamer.freedesktop.org/data/pkg/android/1.24.0/gstreamer-1.0-android-universal-1.24.0.tar.xz
        tar -xf gstreamer-1.0-android-universal-1.24.0.tar.xz
        popd
    - name: Get nnstreamer
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer
        path: nnstreamer
    - name: Get nnstreamer-edge
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer-edge
        path: nnstreamer-edge
    - name: Get nnstreamer-android-resource
      uses: actions/checkout@v4
      with:
        repository: nnstreamer/nnstreamer-android-resource
        path: nnstreamer-android-resource
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: -${{ github.event.pull_request.commits }}
        path: api
    - name: NDK build
      run: |
        export GSTREAMER_ROOT_ANDROID=~/android/gst_root_android/
        export NNSTREAMER_ROOT=${{ github.workspace }}/nnstreamer
        export NNSTREAMER_EDGE_ROOT=${{ github.workspace }}/nnstreamer-edge
        export NNSTREAMER_ANDROID_RESOURCE=${{ github.workspace }}/nnstreamer-android-resource
        export ML_API_ROOT=${{ github.workspace }}/api
        export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
        if [ ${{ matrix.abi }} == 'arm64-v8a' ]; then
          bash ${{ github.workspace }}/api/java/build-nnstreamer-android.sh --target_abi=${{ matrix.abi }}
        elif [ ${{ matrix.abi }} == 'armeabi-v7a' ]; then
          bash ${{ github.workspace }}/api/java/build-nnstreamer-android.sh --target_abi=${{ matrix.abi }} --enable_nnfw=no
        else
          bash ${{ github.workspace }}/api/java/build-nnstreamer-android.sh --target_abi=${{ matrix.abi }} --enable_nnfw=no --enable_tflite=no
        fi

        result=$?
        if [[ ${result} -ne 0 ]]; then
          echo "NDK build failed"
          exit 1
        fi
    - name: Upload android library
      uses: actions/upload-artifact@v4
      with:
        name: android_lib_${{ matrix.abi }}
        path: ${{ github.workspace }}/api/android_lib
