name: Android Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64']
    steps:
    - name: Prepare Android build
      uses: ./.github/actions/android-build
      with:
        mode: ${{ matrix.abi }}
    - name: Upload android library
      uses: actions/upload-artifact@v4
      with:
        name: android_lib_${{ matrix.abi }}
        path: ${{ github.workspace }}/api/android_lib
